name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:  # Allow manual triggering

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run cargo-fmt
        run: cargo fmt --all -- --check
      - name: Run cargo-clippy
        run: cargo clippy -- -D warnings
      - name: Build
        run: cargo check --verbose --workspace --all-targets

  # Library tests (run in parallel with "tests" and dpcs)
  test-lib:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Run Tests
        run: cargo test --lib --workspace

  # "test" tests (aka tests in the tests directory)
  test-test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Run Tests
        run: cargo test --test --workspace

  # doc examples test
  test-doc:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Run Tests
        run: cargo test --doc --workspace

  # documentation build
  docs:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name : Build docs
        env:
          RUSTDOCFLAGS: "-D warnings"
        run: cargo doc --no-deps --workspace


  # Conformance tests (compare to existing  implementation)
  conformance-test:
    name: TPC-H Conformance Tests
    runs-on: ubuntu-latest
    needs: [lint, test-lib, test-test, docs]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Make conformance script executable
        run: chmod +x ./tests/conformance.sh

      - name: Run Conformance Tests
        run: ./tests/conformance.sh